package pivotal;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import pivotal.ui.HomePage;
import pivotal.ui.InitialPage;
import pivotal.ui.LoginPage;

import java.util.concurrent.TimeUnit;

public class LoginTest {
    private WebDriver driver;
    private WebDriverWait wait;
    private InitialPage initialPage;
    private LoginPage loginPage;
    private HomePage homePage;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\WebDriver\\bin\\chromedriver.exe");
        driver = new ChromeDriver();
        driver.get("https://www.pivotaltracker.com/");
    }
    @After
    public void tearDown() {
        driver.quit();
    }

    /**
     * Test login to pivotal.
     */
    @Test
    public void login() {
        initialPage = new InitialPage(driver, wait);
        loginPage = new LoginPage(driver, wait);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        initialPage.clickLoginBtn();
        String email = "test.auto2020@protonmail.com";
        String password = "Secret123";
        homePage = loginPage.login(email, password);
        WebElement actual = homePage.getProfileDropDown();
        WebElement expected = driver.findElement(By.xpath("//button[contains(text(),'testauto20201')]"));
        Assert.assertEquals(actual, expected);
    }
}
